# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/desktop/processer/project_final/project_final.cache/wt [current_project]
set_property parent.project_path D:/desktop/processer/project_final/project_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/desktop/processer/project_final/project_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/3B_Add.vhd
  {D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/Lab 3/Lab 3.srcs/sources_1/new/FA.vhd}
  {D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/Lab 3/Lab 3.srcs/sources_1/new/HA.vhd}
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/ID.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/MP_2W3B.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/MP_2W4B.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/MP_8W4B.vhd
  {D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/Lab 3/Lab 3.srcs/sources_1/new/RCA_4.vhd}
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/ROM.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/Lab_06/Lab_06.srcs/sources_1/new/Reg.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/Reg_3B.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/Reg_Bank.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/Seg_7_2.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/SevenSeg.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/imports/processer/Lab_05/Lab_05.srcs/sources_1/new/Slow_Clk.vhd
  D:/desktop/processer/project_final/project_final.srcs/sources_1/new/processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/processer/project_final/project_final.srcs/constrs_1/imports/processer/Basys3Labs.xdc
set_property used_in_implementation false [get_files D:/desktop/processer/project_final/project_final.srcs/constrs_1/imports/processer/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
